# Generated by Django 2.2 on 2019-05-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('officetype', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('deliverystatus', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('divisionname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('regionname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('circlename', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('taluk', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('districtname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('statename', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
            ],
        ),
    ]
