# Generated by Django 2.2 on 2019-05-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Ram Bahadur', max_length=50, null=True)),
                ('username', models.CharField(blank=True, default='10minutes', max_length=10, null=True)),
            ],
        ),
    ]
